- name: Create User
  become: yes
  become_user: root
  user: 
    name: "{{ user }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    shell: /bin/zsh
    password: "$6$0S/FJbCRbMPC14vt$Ph4f4YKhJoMJ0WqWii20W4DMsIjv4aaFbtFiMs/OaPFIOxoFVJI.T3L5/r7V3a83QRJLY/cDHiwMQXVsO.QV21" #password is: changeme
    append: true
    groups:
      - wheel
      - docker
      - lp
      - audio
      - power
      - pulse

- name: Enable sudo for wheel 
  become: yes
  become_user: root
  lineinfile:
     path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
     state: present
     line: "%wheel ALL=(ALL:ALL) ALL"
     validate: /usr/sbin/visudo -cf %s
     create: yes
