- name: Update cache and packages
  become: true
  become_user: root
  community.general.pacman:
    update_cache: yes
    upgrade: yes

- name: Install pacman packages
  become: true
  become_user: root
  community.general.pacman:
    name: "{{ packages }}"
    state: present

- name: Enable NetworkManager
  systemd_service:
    name: NetworkManager.service
    state: started
    enabled: true

- name: Enable bluetooth
  systemd_service:
    name: bluetooth.service
    state: started
    enabled: true

- name: Enable docker
  systemd_service:
    name: docker.service
    state: started
    enabled: true
