- name: Update cache and packages
  become: true
  become_user: root
  community.general.pacman:
    update_cache: yes
    upgrade: yes

- name: Configure mirrorlist
  become: yes
  become_user: root
  command: "{{ item }}"
  loop:
    - "pacman -S --needed --noconfirm reflector"
    - "reflector --verbose --protocol https -l 5 --sort rate --save /etc/pacman.d/mirrorlist"


